variable "cidr_block_vpc" {}
variable "cidr_block_subnet1a" {}
variable "cidr_block_subnet1b" {}
variable "cidr_block_subnet2" {}
variable "cidr_block_route" {}
variable "cidr_block_ipv6" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "map_public_ip_on_launch" {}
variable "protocol" {}
variable "protocol_egres" {}
variable "port_http" {}
variable "port_https" {}
variable "port_egres" {}
variable "vpc_name" {}
variable "eip_name" {}
variable "nat_name" {}
variable "sg_name" {}
variable "eip_name_2" {}
variable "sg_name_ec2" {}