variable "load_balancer_type" {}
variable "internal" {}
variable "port" {}
variable "protocol" {}
variable "lb_name" {}
variable "lb_type" {}
variable "ami" {}
variable "ec2_name" {}
variable "instance_type" {}
variable "associate_public_ip_address" {}
variable "name_prefix" {}
variable "user_data" {}
variable "resource_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "vrsion" {}
variable "security_group_id" {}
variable "subnet_one_id" {}
variable "subnet_two_id" {}
variable "internetgateway" {}
variable "awsvpc_id" {}
variable "subnet_priv_id" {}
variable "sec_group_ec2_id" {}
variable "lb_sg_id" {}